### ISSUE TITLE
AssertionError : points2D.shape[0] == points3D.shape[0]

### ISSUE THREAD

**Issue by nickzherdev** [heethesh/auro_calibration#40]
For some reason I get this error.  I do point matching according to video tutorial, but after I choose 4 points (5 clicks) on image and 4 points (5 clicks) on cloud and close both windows I get this error. I printed the actual shapes and it was 24 points in 2D list and 82 points in 3D list.

`
(6780, 5)
[INFO] [1633367639.449545]: PCL points available: 6780
[INFO] [1633367643.686074]: IMG: (414.98387096774189, 108.14516129032256)
[INFO] [1633367646.000715]: IMG: (884.6612903225805, 90.080645161290363)
[INFO] [1633367647.348574]: IMG: (845.95161290322562, 397.17741935483866)
[INFO] [1633367648.902774]: IMG: (458.85483870967738, 381.69354838709671)
[INFO] [1633367650.810751]: IMG: (414.98387096774189, 105.56451612903231)
[INFO] [1633367659.856166]: PCL: (1.0405138731002808, -0.75348317623138428, -0.34422934055328369)
[INFO] [1633367661.228198]: PCL: (0.98043715953826904, -0.79111295938491821, 0.021990032866597176)
[INFO] [1633367662.903113]: PCL: (1.1197184324264526, -0.026778703555464745, 0.17739669978618622)
[INFO] [1633367669.163778]: PCL: (1.1925123929977417, 0.088828399777412415, -0.32041797041893005)
[INFO] [1633367670.970556]: PCL: (1.0418047904968262, -0.62920099496841431, -0.32611203193664551)

[WARN] [1633367699.246667]: Updating file: /home/devel/lidar_calib_heethesh_ws/src/lidar_camera_calibration/calibration_data/lidar_camera_calibration/pcl_corners.npy
[WARN] [1633367709.229195]: Updating file: /home/devel/lidar_calib_heethesh_ws/src/lidar_camera_calibration/calibration_data/lidar_camera_calibration/img_corners_rect.npy

[ERROR] [1633367709.261704]: bad callback: <bound method Subscriber.callback of <message_filters.Subscriber object at 0x7f988f7bbd90>>
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/message_filters/__init__.py", line 76, in callback
    self.signalMessage(msg)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/message_filters/__init__.py", line 58, in signalMessage
    cb(*(msg + args))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/message_filters/__init__.py", line 302, in add
    self.signalMessage(*msgs)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/message_filters/__init__.py", line 58, in signalMessage
    cb(*(msg + args))
  File "/home/devel/lidar_calib_heethesh_ws/src/lidar_camera_calibration/scripts/calibrate_camera_lidar.py", line 484, in callback
    calibrate()
  File "/home/devel/lidar_calib_heethesh_ws/src/lidar_camera_calibration/scripts/calibrate_camera_lidar.py", line 325, in calibrate
    assert(points2D.shape[0] == points3D.shape[0])
AssertionError
`

**Comment by heethesh** [comment]
see #27 and #6, delete .npy temp files

**Comment by nickzherdev** [comment]
Thank you!
